### ISSUE TITLE
fibs lazy list should have go 0 1 instead of go 1 0 to make the stream start at 0 .

### ISSUE THREAD

**Issue by javinator48** [tsani/comp-302-review#10]
let rec fib : int str =
    let rec go n m =
      {hd = n;
       tl = Susp (fun () -> go (n+m) n)}
    in
    go 0 1 ; (*instead of go 1 0 to make stream start at 0*)

**Comment by tsani** [comment]
Good catch! Thanks. The problem statement does say that the 0th fibonacci number is 0, not 1.
