### ISSUE TITLE
for_all' and exists'

### ISSUE THREAD

**Issue by David260571230** [tsani/comp-302-review#4]
Both of the solutions for these problems (where we are supposed to implement for_all' with exists, and exists' with for_all) have the wrong type signature, thus not allowing a predicate function to be passed in, only a boolean.

`val for_all' : bool -> 'a mylist -> bool = <fun>`
`val exists' : bool -> 'a mylist -> bool = <fun>`

Here is the solution I have created, which seems inelegant but works:

`let rec for_all' p l =`
`if exists p l = false then false else `
`let Cons(x,xs) = l in if exists p l then exists p xs else false`

`let rec exists' p l = `
`if for_all p l then true else`
`let Cons(x,xs) = l in if for_all p l = false then for_all p xs else true`

With types:

`val for_all' : ('a -> bool) -> 'a mylist -> bool = <fun>`
`val exists' : ('a -> bool) -> 'a mylist -> bool = <fun>`

**Comment by tsani** [comment]
Thanks for spotting the incorrect solutions. I've corrected them. The missing piece of the solutions that were posted was to apply `p` to `x`. Then `p` correctly has its type inferred as `'a -> bool`.

**Comment by tsani** [comment]
By the way, the trick for implementing `forall` in terms of `exists` is to "flip" `p` by doing `fun x -> not (p x)`.
In other words, if there _does not_ exist an `x` such that `p x` is _not_ true, then it must be the case that _all_ `x` are such that `p x` is true. The converse applies for the other direction.
